/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.doktor;

import controller.KlijentKontroler;
import domen.Doktor;
import form.FormEnum;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN 10
 */
public class NewDoktor extends javax.swing.JDialog {

    /**
     * Creates new form NewDoktor
     */
    private Doktor doktor;
    private FormEnum formEnum;
            
    public NewDoktor(java.awt.Frame parent, boolean modal,form.FormEnum formEnum,Doktor doktor) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.formEnum = formEnum;
        this.doktor = doktor;
        
        if(formEnum.equals(FormEnum.IZMENA)){
            txtIme.setText(doktor.getIme());
            txtprezime.setText(doktor.getPrezime());
            txtJmbg.setText(doktor.getJmbg());
            txttelefon.setText(doktor.getTelefon());
            cmbSpecijalizacije.setSelectedItem(doktor.getSpecijalizaija());
            btnDodaj.setText("Izmeni");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtprezime = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        txttelefon = new javax.swing.JTextField();
        cmbSpecijalizacije = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Specijalizacija");

        jLabel4.setText("JMBG");

        jLabel5.setText("Telefon");

        cmbSpecijalizacije.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ginekologija", "Neurologija", "Kardiologija", "Oftamologija", "Dermatologija", "Plasticna hirurgija" }));

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(txttelefon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbSpecijalizacije, 0, 164, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(txtprezime)
                                    .addComponent(txtJmbg)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnIzadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodaj)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtprezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSpecijalizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzadji))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try{
            String ime = txtIme.getText();
            String prezime= txtprezime.getText();
            String jmbg = txtJmbg.getText();
            String telefon = txttelefon.getText();
            String specijalijalizacija = (String) cmbSpecijalizacije.getSelectedItem();
            if(ime.isEmpty()){
                throw new Exception("Niste uneli ime");
            }
            if(prezime.isEmpty()){
                throw new Exception("Niste uneli prezime");
            }
            
            if(telefon.isEmpty()){
                throw new Exception("Niste uneli broj telefona");
                
            }
            if(jmbg.isEmpty()){
                throw new Exception("Niste uneli JMBG");
            }
            if(jmbg.length()!= 13){
                throw new Exception("Niste uneli dobro jmbg, mora da sadrzi 13 cifara!");
            }
            for(int i=0;i<jmbg.length();i++){
                if(!Character.isDigit(jmbg.charAt(i))){
                    throw new Exception("Niste dobro uneli jmbg, mora da bude broj");
                }
            }
            for(int i =0;i<telefon.length();i++){
                if(!Character.isDigit(telefon.charAt(i))){
                    throw new Exception("Niste dobro uneli broj telefona!");
                }
            }
            doktor.setIme(ime);
            doktor.setPrezime(prezime);
            doktor.setJmbg(jmbg);
            doktor.setSpecijalizaija(specijalijalizacija);
            doktor.setTelefon(telefon);
            
            if(formEnum.equals(FormEnum.NOVI)){
                KlijentKontroler.getInstance().addDoktor(doktor);
                JOptionPane.showMessageDialog(this, "Uspesno ste dodali doktora");
            }else{
                KlijentKontroler.getInstance().editDoktor(doktor);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili doktora");

            }
            this.dispose();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Greska",JOptionPane.ERROR_MESSAGE);;
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JComboBox<String> cmbSpecijalizacije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtprezime;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
