/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.termin;

import controller.KlijentKontroler;
import domen.Doktor;
import domen.Pacijent;
import domen.Termin;
import form.FormEnum;
import form.doktor.TableModelDoktor;
import form.pacijent.TableModelPacijent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN 10
 */
public class NewTermin extends javax.swing.JDialog {

    /**
     * Creates new form NewTermin
     */
    private TableModelPacijent tableModelPacijent;
    private Termin termin;
    private Doktor doktor;
    
    public NewTermin(java.awt.Frame parent, boolean modal,Termin termin, Doktor doktor) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.termin = termin;
        this.doktor = doktor;
        popuniForm();
        
        
        
        
        try {
            List<Pacijent> lista = KlijentKontroler.getInstance().getAllPacijenti();
            tableModelPacijent = new TableModelPacijent(lista);
            tblPacijent.setModel(tableModelPacijent);
            if(doktor!= null){
                cmbDoktor.setSelectedItem(doktor);
            }
        } catch (IOException ex) {
            Logger.getLogger(NewTermin.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(NewTermin.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        txtIntervencija = new javax.swing.JTextField();
        cmbDoktor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnZakazi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPacijent = new javax.swing.JTable();
        btnIzadji = new javax.swing.JButton();
        txtPacijent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Intervencija");

        jLabel4.setText("Pacijent");

        jLabel5.setText("Doktor");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Datum uneti u formatu \"dd.MM.yyyy hh:mm\"");

        btnZakazi.setText("Zakazi");
        btnZakazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZakaziActionPerformed(evt);
            }
        });

        tblPacijent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPacijent);

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        txtPacijent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPacijentKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnZakazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(616, 616, 616)
                                .addComponent(btnIzadji))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbDoktor, javax.swing.GroupLayout.Alignment.LEADING, 0, 638, Short.MAX_VALUE)
                                .addComponent(txtPacijent, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIntervencija, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnZakazi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntervencija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnIzadji)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZakaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZakaziActionPerformed
        try{
            String datumZak = txtDatum.getText();
            if(datumZak.isEmpty()){
                throw new Exception("Niste uneli datum");
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy. hh:mm");
            Date datum = sdf.parse(datumZak);
            if(datum.before(new Date())){
                throw new Exception("Dogadjaj se desio u proslosti");
            }

            
            String intervencija = txtIntervencija.getText();
            if(intervencija.isEmpty()){
                throw new Exception("Niste uneli intervenciju");
            }
            
            Doktor doktor = (Doktor) cmbDoktor.getSelectedItem();
            termin.setDatum(datum);
            termin.setIntervencija(intervencija);
            termin.setTehnicar(session.Sesija.getInstance().getTrenutnoUlogovan());
            int red = tblPacijent.getSelectedRow();
            Pacijent pacijent = new Pacijent();
            if(red>-1){
                pacijent =tableModelPacijent.getSelectedRow(red);
            }else{
                throw new Exception("Morate da izaberete iz tabele");
            }
            termin.setPacijent(pacijent);
            termin.setDoktor(doktor);
            
            KlijentKontroler.getInstance().addTermin(termin);
            JOptionPane.showMessageDialog(this, "Uspesno ste zakazali termin");
            
            this.dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
    }//GEN-LAST:event_btnZakaziActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void txtPacijentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPacijentKeyReleased
         try{
            String parametar = txtPacijent.getText().trim();
            List<Pacijent> lista;

            if(parametar.isEmpty()){
                lista = KlijentKontroler.getInstance().getAllPacijenti();
            }else{
                lista = KlijentKontroler.getInstance().searchPacijent(parametar);
                
            }
            tableModelPacijent.setLista(lista);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_txtPacijentKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnZakazi;
    private javax.swing.JComboBox<Object> cmbDoktor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPacijent;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtIntervencija;
    private javax.swing.JTextField txtPacijent;
    // End of variables declaration//GEN-END:variables

    private void popuniForm() {
        try{
            List<Doktor> listaDoktora = KlijentKontroler.getInstance().getAllDoktor();
            List<Pacijent> listaPacijenata = KlijentKontroler.getInstance().getAllPacijenti();
            
            for(Doktor dok: listaDoktora){
                cmbDoktor.addItem(dok);
            }
            
                    
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

   
}
