/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.pacijent;

import controller.KlijentKontroler;
import domen.Pacijent;
import form.FormEnum;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN 10
 */
public class NewPacijent extends javax.swing.JDialog {

    /**
     * Creates new form NewPacijent
     */
    private Pacijent pacijent;
    private FormEnum formEnum;
    public NewPacijent(java.awt.Frame parent, boolean modal,FormEnum formEnum,Pacijent pacijent) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.formEnum = formEnum;
        this.pacijent = pacijent;
        setTitle("Novi pacijent");
        
        if(formEnum.equals(FormEnum.IZMENA)){
            txtIme.setText(pacijent.getIme());
            txtPrezime.setText(pacijent.getPrezime());
            txtJmbg.setText(pacijent.getJmbg());
            txtTelefon.setText(pacijent.getTelefon());
            txtAdresa.setText(pacijent.getAdresa());
            btnDodaj.setText("Izmeni");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("JMBG");

        jLabel4.setText("Adresa");

        jLabel5.setText("Telefon");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(txtPrezime)
                            .addComponent(txtJmbg)
                            .addComponent(txtAdresa)
                            .addComponent(txtTelefon)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnIzadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(btnDodaj)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtAdresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzadji))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try{
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String adresa = txtAdresa.getText();
            String jmbg = txtJmbg.getText().trim();
            String telefon =txtTelefon.getText();
            if(ime.isEmpty()){
                throw new Exception("Niste uneli ime");
            }
            if(prezime.isEmpty()){
                throw new Exception("Niste uneli prezime");
                
            }
            if(adresa.isEmpty()){
                throw new Exception("Niste uneli adresu");
            }
            if(telefon.isEmpty()){
                throw new Exception("Niste uneli broj telefona");
                
            }
            if(jmbg.isEmpty()){
                throw new Exception("Niste uneli JMBG");
            }
            if(jmbg.length()!= 13){
                throw new Exception("Niste uneli dobro jmbg, mora da sadrzi 13 cifara!");
            }
            for(int i=0;i<jmbg.length();i++){
                if(!Character.isDigit(jmbg.charAt(i))){
                    throw new Exception("Niste dobro uneli jmbg, mora da bude broj");
                }
            }
            for(int i =0;i<telefon.length();i++){
                if(!Character.isDigit(telefon.charAt(i))){
                    throw new Exception("Niste dobro uneli broj telefona!");
                }
            }
            pacijent.setIme(ime);
            pacijent.setPrezime(prezime);
            pacijent.setJmbg(jmbg);
            pacijent.setAdresa(adresa);
            pacijent.setTelefon(telefon);

            if(formEnum.equals(FormEnum.NOVI)){
                KlijentKontroler.getInstance().addPacijent(pacijent);
                JOptionPane.showMessageDialog(this, "Uspesno ste uneli pacijenta!");
            }else{
                KlijentKontroler.getInstance().editPacijent(pacijent);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili podatke od pacijenta");
            }
            this.dispose();
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Greska",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
