/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.pacijent;

import controller.KlijentKontroler;
import domen.Pacijent;
import form.FormEnum;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN 10
 */
public class SearchPacijent extends javax.swing.JDialog {

    /**
     * Creates new form SearchPacijent
     */
    private TableModelPacijent tableModelPacijent;
    
    public SearchPacijent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        setTableModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPacijent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacijenti = new javax.swing.JTable();
        btnizmeni = new javax.swing.JButton();
        btnizadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pacijent");

        txtPacijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacijentActionPerformed(evt);
            }
        });
        txtPacijent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPacijentKeyReleased(evt);
            }
        });

        tblPacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPacijenti);

        btnizmeni.setText("Izmeni");
        btnizmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizmeniActionPerformed(evt);
            }
        });

        btnizadji.setText("Izadji");
        btnizadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnizadji)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnizmeni))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnizmeni))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnizadji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPacijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacijentActionPerformed
        
    }//GEN-LAST:event_txtPacijentActionPerformed

    private void txtPacijentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPacijentKeyReleased
        try{
            String parametar = txtPacijent.getText().trim();
            List<Pacijent> lista;

            if(parametar.isEmpty()){
                lista = KlijentKontroler.getInstance().getAllPacijenti();
            }else{
                lista = KlijentKontroler.getInstance().searchPacijent(parametar);
                
            }
            tableModelPacijent.setLista(lista);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_txtPacijentKeyReleased

    private void btnizmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizmeniActionPerformed
        try{
            int red= tblPacijenti.getSelectedRow();
            if(red>=0){
                Pacijent pacijent = tableModelPacijent.getSelectedRow(red);
                new NewPacijent((Frame)this.getParent(), rootPaneCheckingEnabled, FormEnum.IZMENA, pacijent).setVisible(true);
                this.dispose();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnizmeniActionPerformed

    private void btnizadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizadjiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnizadjiActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnizadji;
    private javax.swing.JButton btnizmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacijenti;
    private javax.swing.JTextField txtPacijent;
    // End of variables declaration//GEN-END:variables

    private void setTableModel() {
        try{
            List<Pacijent> lista = KlijentKontroler.getInstance().getAllPacijenti();
            tableModelPacijent = new TableModelPacijent(lista);
            tblPacijenti.setModel(tableModelPacijent);
          
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
